# Site settings
title: Omkar Balekundri Portfolio
description: I am a Software Engineer with focus in Machine Learning
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Omkar Balekundri
user_description: A tech enthusiast who loves developing projects that solve real-world problems.
user_title: Software Developer (Machine learning)
email: omkarbalekundri77@gmail.com
github_username:  omkar-79

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
